In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
train = pd.read_csv('data/sonar_train.csv')
test = pd.read_csv('data/sonar_test.csv')

In [23]:
train.head()

M0      M1      M2      M3      M4      M5      M6      M7      M8  \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       M9  ...     M51     M52     M53     M54     M55     M56     M57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

      M58     M59   Class  
0  0.0090  0.0032       R  
1  0.0052  0.0044       R  
2  0.0095  0.0078       R  
3  0.0040  0.0117       R  
4  0.0107  0.0094       R  

[5 rows x 61 columns]

In [24]:
train = train.rename(columns={' Class':'class'})
test = test.rename(columns={' Class':'class'})

In [25]:
train = np.array(train)

In [26]:
train

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.034, 0.0625, 0.0381, ..., 0.0033, 0.0058, 'M'],
       [0.0209, 0.0191, 0.0411, ..., 0.007, 0.0042, 'M'],
       [0.0368, 0.0279, 0.0103, ..., 0.011, 0.0052, 'M']], dtype=object)

In [27]:
train.shape

(188, 61)

In [28]:
train.transpose()

array([[0.02, 0.0453, 0.0262, ..., 0.034, 0.0209, 0.0368],
       [0.0371, 0.0523, 0.0582, ..., 0.0625, 0.0191, 0.0279],
       [0.0428, 0.0843, 0.1099, ..., 0.0381, 0.0411, 0.0103],
       ...,
       [0.009, 0.0052, 0.0095, ..., 0.0033, 0.007, 0.011],
       [0.0032, 0.0044, 0.0078, ..., 0.0058, 0.0042, 0.0052],
       ['R', 'R', 'R', ..., 'M', 'M', 'M']], dtype=object)

In [29]:
np.random.shuffle(train)
train

array([[0.0298, 0.0615, 0.065, ..., 0.02, 0.0073, 'R'],
       [0.01, 0.0275, 0.019, ..., 0.0091, 0.0058, 'R'],
       [0.0231, 0.0351, 0.003, ..., 0.0043, 0.003, 'R'],
       ...,
       [0.0117, 0.0069, 0.0279, ..., 0.0026, 0.0052, 'M'],
       [0.0443, 0.0446, 0.0235, ..., 0.0152, 0.01, 'M'],
       [0.0015, 0.0186, 0.0289, ..., 0.0032, 0.0047, 'M']], dtype=object)

In [30]:
train = train.transpose()
train

array([[0.0298, 0.01, 0.0231, ..., 0.0117, 0.0443, 0.0015],
       [0.0615, 0.0275, 0.0351, ..., 0.0069, 0.0446, 0.0186],
       [0.065, 0.019, 0.003, ..., 0.0279, 0.0235, 0.0289],
       ...,
       [0.02, 0.0091, 0.0043, ..., 0.0026, 0.0152, 0.0032],
       [0.0073, 0.0058, 0.003, ..., 0.0052, 0.01, 0.0047],
       ['R', 'R', 'R', ..., 'M', 'M', 'M']], dtype=object)

In [31]:
train[-1]

array(['R', 'R', 'R', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M',
       'R', 'R', 'R', 'R', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'M',
       'M', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'M',
       'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R',
       'M', 'R', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'M',
       'R', 'R', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R',
       'R', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'M', 'R',
       'M', 'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'M',
       'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'M',
       'R', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'R', 'M',
       'R', 'R', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'R

In [33]:
trainX, trainY = train[:-1],train[-1]

In [35]:
trainY

array(['R', 'R', 'R', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M',
       'R', 'R', 'R', 'R', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'M',
       'M', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'M',
       'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R',
       'M', 'R', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'M',
       'R', 'R', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R',
       'R', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'M', 'R',
       'M', 'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'M',
       'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'M',
       'R', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'R', 'M',
       'R', 'R', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'R

In [110]:
trainX.shape

(60, 188)

In [169]:
def init_params():
    w1 = np.random.rand(10,60) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    
    w2 = np.random.rand(2,10) - 0.5
    b2 = np.random.rand(2,1) - 0.5
    
    return w1, b1, w2, b2

In [82]:
def relu(z):
    return np.maximum(0,z)

In [83]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z))

In [170]:
def forwardProp(w1, b1, w2, b2, X):
    z1 = w1.dot(X) + b1
    a1 = relu(z1)
    
    z2 = w2.dot(a1) + b2
    a2 = softmax(z2)
    
    return z1, a1, z2, a2

In [86]:
def getReLuDerivative(Z):
    return Z > 0

In [164]:
def backProp(z1, a1, z2, a2, w2, X, Y):
    m = Y.size
    oneHotY = oneHot(Y)
    dZ2 = a2 - oneHotY
    dW2 = 1/m * dZ2.dot(a1.transpose())
    db2 = 1/m * np.sum(dZ2)
    
    dZ1 = w2.transpose().dot(dZ2) * getReLuDerivative(z1)
    dW1 = 1/m * dZ1.dot(X.transpose())
    db1 = 1/m * np.sum(dZ1)
    
    return dW1, db1, dW2, db2

In [88]:
def updateParams(dW1, db1, dW2, db2, w1, b1, w2, b2, alpha):
    w1 = w1 - alpha*dW1
    b1 = b1 - alpha*db1
    w2 = w2 - alpha*dW2
    b2 = b2 - alpha*db2
    
    return w1, b1, w2, b2

In [200]:
def getPredictions(a2):
    return np.argmax(a2, 0)

def getAccuracy(predictions,Y):
    #print(predictions,Y)
    return np.sum(predictions == Y) / Y.size

In [201]:
def gradientDescent(X, Y, epochs, lr):
    w1, b1, w2, b2 = init_params()
    
    for i in range(epochs):
        z1, a1, z2, a2 = forwardProp(w1, b1, w2, b2, X)
        dW1, db1, dW2, db2 = backProp(z1, a1, z2, a2, w2, X, Y)
        w1, b1, w2, b2 = updateParams(dW1, db1, dW2, db2, w1, b1, w2, b2, lr)
        
        if i%10 == 0:
            #print(a2)
            print(f'Iteration {i}')
            print('Accuracy:',getAccuracy(getPredictions(a2), maskY(Y)))
            
    return w1, b1, w2, b2

In [64]:
trainX = trainX.astype(float)

In [65]:
trainX.dtype

dtype('float64')

In [97]:
def maskY(Y):
    masked = (Y == 'M')
    return masked.astype(int)

In [99]:
print(len(maskY(trainY)))

188


In [130]:
def oneHot(Y):
    Y = maskY(Y)
    oneHotY = np.zeros((Y.size, Y.max()+1))
    oneHotY[np.arange(Y.size),Y] = 1
            
    return oneHotY.transpose()

In [166]:
w1, b1, w2, b2 = gradientDescent(trainX, trainY, 100, 0.1)

[[8.46278051e-11 1.70413630e-13 1.51500404e-13 2.34965521e-15
  2.34199071e-10 7.30979415e-13 3.73090154e-09 7.73587284e-07
  8.83303369e-09 1.23238588e-12 6.44758965e-15 5.33805364e-19
  4.52372883e-11 1.18056857e-11 9.73461917e-13 1.10380575e-12
  1.90552436e-13 4.85498135e-19 1.84252338e-07 1.33413268e-11
  1.43521889e-10 7.83847702e-12 2.86260443e-13 2.44596348e-11
  1.03522888e-08 1.94704622e-14 3.68622167e-08 8.55537810e-09
  1.00011610e-12 8.86566029e-10 1.10883237e-11 1.16813636e-17
  3.45007203e-11 1.35324726e-10 3.52145694e-14 2.95058614e-08
  5.94604708e-11 9.73614140e-09 1.98033487e-11 2.25359381e-09
  9.60985183e-11 5.40518967e-18 1.00169693e-14 3.27048442e-09
  1.76342070e-12 8.32060942e-09 2.92660765e-12 1.90977225e-08
  1.81718189e-12 5.06033409e-11 3.39732458e-14 1.98970104e-13
  2.18506188e-07 3.23053838e-14 2.86884108e-13 7.25431708e-11
  7.12457589e-14 1.09104263e-13 1.40552392e-18 3.67205762e-13
  1.77768279e-15 3.98523645e-13 5.22844450e-14 2.70386939e-13
  1.3903

/var/folders/b7/hbtzj39j4tng96ln0jphxwzr0000gn/T/ipykernel_2811/53734546.py:2: RuntimeWarning: overflow encountered in exp
  return np.exp(z) / np.sum(np.exp(z))
/var/folders/b7/hbtzj39j4tng96ln0jphxwzr0000gn/T/ipykernel_2811/53734546.py:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(z) / np.sum(np.exp(z))


[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  n

In [168]:
w1, b1, w2, b2 = gradientDescent(trainX, trainY, 100, 1e-4)

[[8.25386001e-05 2.22145710e-07 1.64151660e-07 3.76566095e-09
  4.44900983e-04 7.51560010e-07 2.26109839e-03 5.22577144e-02
  2.94910682e-03 1.02044926e-06 1.41293035e-08 1.35485840e-12
  3.05028325e-05 1.10788634e-05 6.92019704e-07 1.01114763e-06
  1.97215159e-07 1.48048011e-12 1.44589178e-02 1.43537464e-05
  6.62976890e-05 1.61812434e-05 2.01372365e-07 2.34926191e-05
  1.14641976e-03 4.99511396e-08 2.29357875e-03 6.23793046e-03
  7.36065035e-07 3.26829297e-04 1.52915567e-06 1.21151963e-10
  1.70764421e-05 7.89758209e-05 7.28326014e-08 7.82507503e-04
  2.42193703e-05 3.52509177e-03 1.52615810e-05 6.16801871e-05
  4.37500083e-05 2.88618066e-11 2.96099065e-08 2.96435435e-03
  6.61680546e-07 2.43562800e-04 3.30136094e-06 1.51187110e-03
  1.25869480e-06 1.77360513e-05 6.85477715e-08 1.61596585e-07
  9.53626894e-03 2.68162562e-08 3.28798089e-07 5.95442340e-05
  1.26402331e-07 1.29278778e-07 3.40696251e-12 2.14519953e-07
  3.13669902e-09 2.76153746e-07 7.14100526e-08 2.59833607e-07
  7.6444

[[3.64247713e-05 5.53583246e-08 4.06259186e-08 6.11163764e-10
  2.36461480e-04 2.16355995e-07 1.46193719e-03 4.58637498e-02
  1.91818377e-03 2.95388145e-07 2.64294950e-09 9.89301555e-14
  1.26486063e-05 4.22036993e-06 1.90370292e-07 3.07838314e-07
  4.86199778e-08 1.09268657e-13 1.10821253e-02 5.55437603e-06
  2.96728854e-05 6.05632183e-06 4.96443825e-08 9.56711982e-06
  6.75448533e-04 1.08784480e-08 1.44061981e-03 4.34641596e-03
  2.05607938e-07 1.74435076e-04 4.65643271e-07 1.35863186e-11
  6.97951015e-06 3.62478464e-05 1.62565364e-08 4.53676492e-04
  9.56104132e-06 2.37132769e-03 5.84995262e-06 2.68855579e-05
  1.87994361e-05 2.81815014e-12 5.87071854e-09 1.88010945e-03
  1.82777071e-07 1.22502161e-04 1.08557364e-06 9.14676977e-04
  3.72803023e-07 6.88954737e-06 1.46979679e-08 3.77088098e-08
  6.99680543e-03 5.35584646e-09 8.46592255e-08 2.66403841e-05
  3.00609359e-08 3.00152316e-08 2.72458921e-13 5.21826324e-08
  5.06468657e-10 6.99051590e-08 1.55854504e-08 6.32473422e-08
  4.2354

In [199]:
w1, b1, w2, b2 = gradientDescent(trainX, trainY, 100, 1e-5)

[[0.00363635 0.00231322 0.00261751 0.00212915 0.00237748 0.00266327
  0.00201912 0.00237832 0.00220736 0.00255455 0.00329217 0.00352963
  0.00213297 0.00267873 0.0037916  0.00240248 0.00266207 0.00342977
  0.00233275 0.00171245 0.00236499 0.00258256 0.00307923 0.00195845
  0.00298747 0.0024542  0.00373104 0.00283966 0.00298714 0.00211978
  0.00371265 0.00302654 0.00246107 0.00271456 0.00249737 0.00236834
  0.00247567 0.00257055 0.0020712  0.00334749 0.00205628 0.00295326
  0.00301653 0.00231254 0.00323747 0.00308238 0.00308687 0.0033714
  0.00291586 0.00266622 0.00302733 0.00332953 0.00271273 0.00288511
  0.00254339 0.00220068 0.00227238 0.00315637 0.00348504 0.00319079
  0.00262452 0.00260719 0.00260492 0.00425872 0.00251874 0.00332276
  0.00396714 0.00197409 0.00337798 0.00235165 0.00195218 0.00351788
  0.00214641 0.00260777 0.0028727  0.0026016  0.00220859 0.00315006
  0.00242789 0.0025861  0.00307293 0.00375343 0.00374437 0.0033157
  0.0020006  0.00237551 0.0027076  0.00255204 0.00

In [205]:
w1, b1, w2, b2 = gradientDescent(trainX, trainY, 100, 1e-4)

Iteration 0
Accuracy: 0.6702127659574468
Iteration 10
Accuracy: 0.6702127659574468
Iteration 20
Accuracy: 0.6702127659574468
Iteration 30
Accuracy: 0.6702127659574468
Iteration 40
Accuracy: 0.6702127659574468
Iteration 50
Accuracy: 0.6648936170212766
Iteration 60
Accuracy: 0.6648936170212766
Iteration 70
Accuracy: 0.6648936170212766
Iteration 80
Accuracy: 0.6648936170212766
Iteration 90
Accuracy: 0.6648936170212766


In [208]:
w1, b1, w2, b2 = gradientDescent(trainX, trainY, 100, 9e-3)

Iteration 0
Accuracy: 0.5425531914893617
Iteration 10
Accuracy: 0.5478723404255319
Iteration 20
Accuracy: 0.5478723404255319
Iteration 30
Accuracy: 0.5638297872340425
Iteration 40
Accuracy: 0.5638297872340425
Iteration 50
Accuracy: 0.5797872340425532
Iteration 60
Accuracy: 0.5904255319148937
Iteration 70
Accuracy: 0.5372340425531915
Iteration 80
Accuracy: 0.48936170212765956
Iteration 90
Accuracy: 0.48404255319148937
