In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [7]:
train = pd.read_csv('data/sonar_train.csv').rename(columns={' Class':'class'})
test = pd.read_csv('data/sonar_test.csv').rename(columns={' Class':'class'})

In [8]:
test

M0      M1      M2      M3      M4      M5      M6      M7      M8  \
0   0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1   0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2   0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3   0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4   0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
5   0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
6   0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
7   0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
8   0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
9   0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   
10  0.0039  0.0063  0.0152  0.0336  0.0310  0.0284  0.0396  0.0272  0.0323   
11  0.0123  0.0309  0.0169  0.0313  0.0358  0.0102  0.0182  0.0579  0.1122   
12  0.0079  0.0086  0.0055  0.0250  0.0344  0.0546  0.0528  0.0958  0.1009   
13  0.0090  0.0062  0.0253  0.0489  0.1197  0.1589  0.1392  0.0987  0.0955   
14  0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
15  0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459   
16  0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466   
17  0.0192  0.0607  0.0378  0.0774  0.1388  0.0809  0.0568  0.0219  0.1037   
18  0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794   
19  0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   
20  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
21  0.0158  0.0239  0.0150  0.0494  0.0988  0.1425  0.1463  0.1219  0.1697   
22  0.0156  0.0210  0.0282  0.0596  0.0462  0.0779  0.1365  0.0780  0.1038   
23  0.0315  0.0252  0.0167  0.0479  0.0902  0.1057  0.1024  0.1209  0.1241   
24  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673   
25  0.0203  0.0121  0.0380  0.0128  0.0537  0.0874  0.1021  0.0852  0.1136   
26  0.0392  0.0108  0.0267  0.0257  0.0410  0.0491  0.1053  0.1690  0.2105   
27  0.0129  0.0141  0.0309  0.0375  0.0767  0.0787  0.0662  0.1108  0.1777   
28  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879  0.1220  0.1977   
29  0.0366  0.0421  0.0504  0.0250  0.0596  0.0252  0.0958  0.0991  0.1419   
30  0.0238  0.0318  0.0422  0.0399  0.0788  0.0766  0.0881  0.1143  0.1594   
31  0.0116  0.0744  0.0367  0.0225  0.0076  0.0545  0.1110  0.1069  0.1708   
32  0.0131  0.0387  0.0329  0.0078  0.0721  0.1341  0.1626  0.1902  0.2610   
33  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865   
34  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
35  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
36  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
37  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
38  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
39  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        M9  ...     M51     M52     M53     M54     M55     M56     M57  \
0   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1   0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2   0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3   0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4   0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
5   0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
6   0.3513  ...  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092  0.0143   
7   0.2838  ...  0.0081  0.0120  0.0045  0.0121  0.0097  0.0085  0.0047   
8   0.1487  ...  0.0145  0.0128  0.0145  0.0058  0.0049  0.0065  0.0093   
9   0.0251  ...  0.0090  0.0223  0.0179  0.0084  0.0068  0.

In [12]:
labels = {0: 'Rock', 1: 'Mine'}

def defineClass(label):
    return 1 if label == 'M' else 0

In [200]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe.rename(columns={' Class':'class'})
        self.dataframe['class'] = self.dataframe["class"].apply(defineClass)
        
    def __getitem__(self, index):
        row = self.dataframe.iloc[index].to_numpy()
        features = row[:-1]
        label = row[-1]    
        return features, label
    
    def __len__(self):
        return len(self.dataframe)

In [201]:
batchSize = 4
trainData = CustomDataset(dataframe = train)
trainLoader = DataLoader(trainData,batch_size=batchSize,shuffle=True)

In [202]:
sampler = iter(trainLoader)
print(next(sampler))

[tensor([[0.0317, 0.0956, 0.1321, 0.1408, 0.1674, 0.1710, 0.0731, 0.1401, 0.2083,
         0.3513, 0.1786, 0.0658, 0.0513, 0.3752, 0.5419, 0.5440, 0.5150, 0.4262,
         0.2024, 0.4233, 0.7723, 0.9735, 0.9390, 0.5559, 0.5268, 0.6826, 0.5713,
         0.5429, 0.2177, 0.2149, 0.5811, 0.6323, 0.2965, 0.1873, 0.2969, 0.5163,
         0.6153, 0.4283, 0.5479, 0.6133, 0.5017, 0.2377, 0.1957, 0.1749, 0.1304,
         0.0597, 0.1124, 0.1047, 0.0507, 0.0159, 0.0195, 0.0201, 0.0248, 0.0131,
         0.0070, 0.0138, 0.0092, 0.0143, 0.0036, 0.0103],
        [0.0223, 0.0375, 0.0484, 0.0475, 0.0647, 0.0591, 0.0753, 0.0098, 0.0684,
         0.1487, 0.1156, 0.1654, 0.3833, 0.3598, 0.1713, 0.1136, 0.0349, 0.3796,
         0.7401, 0.9925, 0.9802, 0.8890, 0.6712, 0.4286, 0.3374, 0.7366, 0.9611,
         0.7353, 0.4856, 0.1594, 0.3007, 0.4096, 0.3170, 0.3305, 0.3408, 0.2186,
         0.2463, 0.2726, 0.1680, 0.2792, 0.2558, 0.1740, 0.2121, 0.1099, 0.0985,
         0.1271, 0.1459, 0.1164, 0.0777, 0.0439, 0

In [203]:
next(sampler)

[tensor([[2.0900e-02, 2.7800e-02, 1.1500e-02, 4.4500e-02, 4.2700e-02, 7.6600e-02,
          1.4580e-01, 1.4300e-01, 1.8940e-01, 1.8530e-01, 1.7480e-01, 1.5560e-01,
          1.4760e-01, 1.3780e-01, 2.5840e-01, 3.8270e-01, 4.7840e-01, 5.3600e-01,
          6.1920e-01, 7.9120e-01, 9.2640e-01, 1.0000e+00, 9.0800e-01, 7.4350e-01,
          5.5570e-01, 3.1720e-01, 1.2950e-01, 5.9800e-02, 2.7220e-01, 3.6160e-01,
          3.2930e-01, 4.8550e-01, 3.9360e-01, 1.8450e-01, 3.4200e-02, 2.4890e-01,
          3.8370e-01, 3.5140e-01, 2.6540e-01, 1.7600e-01, 1.5990e-01, 8.6600e-02,
          5.9000e-02, 8.1300e-02, 4.9200e-02, 4.1700e-02, 4.9500e-02, 3.6700e-02,
          1.1500e-02, 1.1800e-02, 1.3300e-02, 9.6000e-03, 1.4000e-03, 4.9000e-03,
          3.9000e-03, 2.9000e-03, 7.8000e-03, 4.7000e-03, 2.1000e-03, 1.1000e-03],
         [4.7300e-02, 5.0900e-02, 8.1900e-02, 1.2520e-01, 1.7830e-01, 3.0700e-01,
          3.0080e-01, 2.3620e-01, 3.8300e-01, 3.7590e-01, 3.0210e-01, 2.9090e-01,
          2.301

In [294]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net,self).__init__()
        
        self.fc1 = nn.Linear(60,120, dtype=torch.float64)
        self.fc4 = nn.Linear(120,30, dtype=torch.float64)
        self.fc6 = nn.Linear(30,1, dtype=torch.float64)
        
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc4(x))
        x = F.sigmoid(self.fc6(x))
        
        return x

In [295]:
net = Net()

In [296]:
criterion = nn.BCELoss()
optimiser = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)

In [297]:
for epoch in range(20):
    runningLoss = 0.0
    
    for i, data in enumerate(trainLoader,0):
        
        inputs, labels = data
        labels = labels.unsqueeze(1)
        optimiser.zero_grad()
                
        outputs = net(inputs)
        #print(outputs,outputs.shape,labels,labels.shape)

        loss = criterion(outputs, labels)
        loss.backward()
        optimiser.step()
        
        runningLoss += loss.item()
        
    print(f'[{epoch + 1}] loss: {runningLoss / i:.3f}')
    runningLoss = 0.0

[1] loss: 0.710
[2] loss: 0.704
[3] loss: 0.697
[4] loss: 0.698
[5] loss: 0.662
[6] loss: 0.626
[7] loss: 0.555
[8] loss: 0.538
[9] loss: 0.476
[10] loss: 0.486
[11] loss: 0.445
[12] loss: 0.512
[13] loss: 0.502
[14] loss: 0.530
[15] loss: 0.533
[16] loss: 0.532
[17] loss: 0.449
[18] loss: 0.451
[19] loss: 0.406
[20] loss: 0.383


In [298]:
testData = CustomDataset(dataframe = test)
testLoader = DataLoader(testData, batch_size=batchSize, shuffle=True)

In [299]:
sampler = iter(testLoader)
print(next(sampler))

[tensor([[2.0300e-02, 1.2100e-02, 3.8000e-02, 1.2800e-02, 5.3700e-02, 8.7400e-02,
         1.0210e-01, 8.5200e-02, 1.1360e-01, 1.7470e-01, 2.1980e-01, 2.7210e-01,
         2.1050e-01, 1.7270e-01, 2.0400e-01, 1.7860e-01, 1.3180e-01, 2.2600e-01,
         2.3580e-01, 3.1070e-01, 3.9060e-01, 3.6310e-01, 4.8090e-01, 6.5310e-01,
         7.8120e-01, 8.3950e-01, 9.1800e-01, 9.7690e-01, 8.9370e-01, 7.0220e-01,
         6.5000e-01, 5.0690e-01, 3.9030e-01, 3.0090e-01, 1.5650e-01, 9.8500e-02,
         2.2000e-01, 2.2430e-01, 2.7360e-01, 2.1520e-01, 2.4380e-01, 3.1540e-01,
         2.1120e-01, 9.9100e-02, 5.9400e-02, 1.9400e-01, 1.9370e-01, 1.0820e-01,
         3.3600e-02, 1.7700e-02, 2.0900e-02, 1.3400e-02, 9.4000e-03, 4.7000e-03,
         4.5000e-03, 4.2000e-03, 2.8000e-03, 3.6000e-03, 1.3000e-03, 1.6000e-03],
        [1.3100e-02, 3.8700e-02, 3.2900e-02, 7.8000e-03, 7.2100e-02, 1.3410e-01,
         1.6260e-01, 1.9020e-01, 2.6100e-01, 3.1930e-01, 3.4680e-01, 3.7380e-01,
         3.0550e-01, 1.926

In [310]:
correct, total = 0, 0

with torch.no_grad():
    for data in testLoader:
        inputs, labels = data
        labels = labels.unsqueeze(1)
        outputs = net(inputs)
        print('o',outputs)
        #print('r',outputs.round())
        #print('l',labels)
        
        _,predicted = torch.max(outputs,1)
        for label, prediction in zip(labels,outputs.round()):
            print(label,prediction)
            if label == prediction: correct += 1
            total += 1
        print(correct,total,correct/total)
            
print(f'Accuracy on sonar dataset: {100*(correct/total)}%')

o tensor([[0.9469],
        [0.9396],
        [0.2337],
        [0.0087]], dtype=torch.float64)
tensor([1.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([1.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([0.], dtype=torch.float64) tensor([0.], dtype=torch.float64)
tensor([0.], dtype=torch.float64) tensor([0.], dtype=torch.float64)
4 4 1.0
o tensor([[0.6942],
        [0.5570],
        [0.7523],
        [0.4842]], dtype=torch.float64)
tensor([1.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([0.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([1.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([0.], dtype=torch.float64) tensor([0.], dtype=torch.float64)
7 8 0.875
o tensor([[0.2473],
        [0.6296],
        [0.7422],
        [0.9425]], dtype=torch.float64)
tensor([0.], dtype=torch.float64) tensor([0.], dtype=torch.float64)
tensor([1.], dtype=torch.float64) tensor([1.], dtype=torch.float64)
tensor([1.], d